#!/dis/sh
project = $1

if {no $project} {
	echo 'usage: projectsteps $"project'
	exit 1
}

fn stepline {
	proj = $1
	proc = $2
	step = $3

	tmp = /tmp/projectsteps.${pid}
	ectool getStep $"proj $"proc $"step > $tmp
	subproj = `{cat $tmp | os xpath -q -e '//subproject/text()' >[2]/dev/null}
	subproc = `{cat $tmp | os xpath -q -e '//subprocedure/text()' >[2]/dev/null}
	rm $tmp

	if {no $subproc} {
		echo '	'^$"step
	} {
		if {no $subproj} {
			echo '	'^$"step '('^$"subproc^')'
		} {
			echo '	'^$"step '('^$"subproj^':'^$"subproc^')'
		}
	}
}

subfn proceduresteps {
	proj = $1
	proc = $2

	result = `{ectool getSteps $"proj $"proc | os xpath -q -e '//stepName/text()' >[2]/dev/null}
}

fn proceduresteps {
	proj = $1
	proc = $2

	echo $proc
	apply {stepline $"proj $"proc $"1} ${proceduresteps $"proj $"proc}
}

subfn projectprocedures {
	proj = $1

	result = `{ectool getProcedures $"proj | os xpath -q -e '//procedureName/text()'}
}

ifs = '
'; apply {proceduresteps $"project $"1} ${projectprocedures $"project}
