#!/dis/sh
project = $1

if {no $project} {
	echo 'usage: projectcommands $"project'
	exit 1
}

fn procedurepaths {
	proj = $1
	proc = $2

	ectool getSteps $"proj $"proc | os xpath -q -e '//stepName/text()' >[2]/dev/null | sed 's,(.*),/projects['^$proj^']/procedures['^$proc^']/steps[\1]/command,'
}

subfn projectprocedures {
	proj = $1

	result = `{ectool getProcedures $"proj | os xpath -q -e '//procedureName/text()'}
}

ifs = '
'; apply {procedurepaths $"project $"1} ${projectprocedures $"project}
