#!/dis/sh
project = $1

if {no $project} {
	echo 'usage: projectsteps $"project'
	exit 1
}

ifs = '
'; apply {
	procedure = $1
	echo $procedure

	ifs = '
'
	steps = `{ifs = '
'; ectool getSteps $"project $"procedure | os xpath -q -e '//stepName/text()' >[2]/dev/null}

	apply {
		step = $1

		tmp = /tmp/projectsteps.${pid}
		ectool getStep $"project $"procedure $"step > $tmp
		subproject = `{cat $tmp | os xpath -q -e '//subproject/text()' >[2]/dev/null}
		subprocedure = `{cat $tmp | os xpath -q -e '//subprocedure/text()' >[2]/dev/null}
		rm $tmp
	
		if {no $subprocedure} {
			echo '	'^$"step
		} {
			if {no $subproject} {
				echo '	'^$"step '('^$"subprocedure^')'
			} {
				echo '	'^$"step '('^$"subproject^':'^$"subprocedure^')'
			}
		}
	} $steps

} `{ifs = ' 	
'; ectool getProcedures $"project | os xpath -q -e '//procedureName/text()'}
